[manager]
ratio          = [1, 3, 4]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "size"
show_hidden    = false
show_symlink   = true

[preview]
image_filter  = "triangle"
image_quality = 75
tab_size      = 2
max_width     = 600
max_height    = 900
cache_dir     = ""

[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]

[open]
prepend_rules = [
  { url = "*/", use = ["edit", "open"] },
]
rules = [
  { mime = "text/*",  use = ["edit"] },
  { mime = "*/json",  use = ["edit"] },
  { mime = "*/xml",   use = ["edit"] },
  { url  = "*",       use = ["open", "edit"] },
]
